name: Random Stuff - Test Site
favicon: null
layout_spectrum: 0.9943673743400723
typography_spectrum: 0.9612873559817672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6223097569309175
  lightness: 0.5412076225038618
  saturation: 0.4979097987525165
  rhythmicContrast: 0.4520407668314874
purpose: []
